### PR TITLE
fix the db:restore file already exist exception

### PR DESCRIPTION
**Pull request by chromeorfirefox**
fix the db:restore command "file already exist exception".

### CODE REVIEW

**Comment by ShawnMcCool** [comment]
What is the nature of this error? When does it complain?

**Comment by chromeorfirefox** [comment]
it resolves the issue of https://github.com/heybigname/backup-manager/issues/35
steps to reproduce the bug:
1. backup the database to local
 run php artisandb:backup --database="mysql" --compression="gzip" --destination="local" --destinationPath="mysql.bk"

2. try to restore the database from the backup of step 1.
run php artisan db:restore --database="mysql" --compression="gzip" --source="local" --sourcePath="mysql.bk.gz"

the output is:
Downloading and importing backup...


                                          
  [League\Flysystem\FileExistsException]  
  File already exists at path: mysql.bk.gz  

As for the root cause please see samkitano's comment  copied below

Figured it out.

In vendor/heybigname/backup-manager/src/Procedures/RestoreProcedure.php
line 31:
// download or retrieve the archived backup file
$sequence->add(new Tasks\Storage\TransferFile(
$this->filesystems->get($sourceType), $sourcePath,
$localFilesystem, basename($workingFile)
));

Since (in my specific case) we are using local backup files, the procedure adds a Task to "download" the specified file to itself, thus (correctly) generating the error.

If we comment it, the restoration process runs just fine.

I'm guessing it would need to check if we are trying to use a local file or a remote one, before adding the task. We don't have to "download" it, if the file is already on the working directory.

For the moment, I'll just leave the procedure commented, in order to suit my needs for this specific project, (very short deadline), but a fix would be appreciated :)

I'd be happy to help, but I'm affraid this github thing really freaks me out. Total noob, and very little time to read some tutorials, at this time :D

Anyways, great job here, and great idea. Saved me a lot of time. Thanks, Shawn! :)

**Comment by ShawnMcCool** [comment]
I think that what we need to do is add a 'working path' to the configuration for the local adapter and then make it so that the local 'root' path is actually a local 'target' path. The names probably need some work.

The target path would be where the backups and restorations happen to / from. The working folder would be the package's own place to do what it needs to do.

**Comment by rateen** [comment]
@ShawnMcCool We've had the same issue and this did fix it.
Are you going to merge and do a new release so we can update our dependencies and rely on it for production scenarios?

Thanks!
Ertan

**Comment by ShawnMcCool** [comment]
Ok, merged in. I'll update a new version. Thanks for the work.

**Pull request merged**
